name: Router-chain-testnet-ubuntu-22.04-Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Tag binary version"
        required: true

jobs:
  setup:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.21.0"

  build-router-chain:
    needs: setup
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          repository: "router-protocol/router-chain"
          ref: "testnet"
          path: "router-chain"
          token: ${{ secrets.USER_GITHUB_TOKEN }}

      - name: Build router-chain
        run: |
          echo "🛠️ Building router-chain binary"
          echo "uname: $(uname -m)" #x86_64
          echo "GO version: $(go version)"

          cd router-chain
          go mod download
          git config --global user.name "Router Protocol"
          git config --global user.email "infra@routerprotocol.com"
          git tag ${{ github.event.inputs.version }}
          go mod tidy
          make build
          echo "routerd build successful"
          cd ./bin
          tar -czvf .tar.gz routerd
          ls -al
          mkdir -p ${{ github.workspace }}/router-chain-binaries/
          mv routerd.tar.gz ${{ github.workspace }}/router-chain-binaries/
          echo "🔥 routerd.tar.gz created"
          echo "🔥 routerd.tar.gz moved to ${{ github.workspace }}/router-chain-binaries/"
          cd ${{ github.workspace }}/router-chain-binaries/

      - name: Archive router-chain binary
        uses: actions/upload-artifact@v2
        with:
          name: router-chain
          path: ${{ github.workspace }}/router-chain-binaries/routerd.tar.gz

  package-and-push:
    needs: [build-router-chain]
    runs-on: ubuntu-22.04
    steps:
      - name: Download router-chain binary
        uses: actions/download-artifact@v2
        with:
          name: router-chain
          path: ${{ github.workspace }}/router-chain-binaries/

      - uses: actions/checkout@v3
        with:
          repository: "router-protocol/router-chain-testnet-release"
          ref: "ubuntu-build"
          path: "rc-releases"
          token: ${{ secrets.USER_GITHUB_TOKEN }}

      - name: Package and Push new binaries to the current repository
        run: |
          cd rc-releases
          git config --global url."https://ganesh_bhagi:${{secrets.USER_GITHUB_TOKEN}}@github.com/".insteadOf "https://github.com/"
          git config user.name "Router Protocol"
          git config user.email "infra@routerprotocol.com"
          ls -al ${{ github.workspace }}/router-chain-binaries/
          mv ${{ github.workspace }}/router-chain-binaries/routerd.tar.gz ./linux/
          git add linux/routerd.tar.gz
          git commit -m "Latest router-chain executable updated: $(date +'%Y-%m-%d %H:%M:%S')"
          git push